// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJC5CCI0uMg_-bT00OmuXOSGLGE7EXlW4',
    appId: '1:127475219651:web:d6ef4efd259964fa36b676',
    messagingSenderId: '127475219651',
    projectId: 'my-netflix-dup',
    authDomain: 'my-netflix-dup.firebaseapp.com',
    storageBucket: 'my-netflix-dup.appspot.com',
    measurementId: 'G-KB0LGY6099',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIamCQ40SYade8yZt0e0j5p2a3jKXL95g',
    appId: '1:127475219651:android:24a18a904dbfa70236b676',
    messagingSenderId: '127475219651',
    projectId: 'my-netflix-dup',
    storageBucket: 'my-netflix-dup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbsgp1NVQLla381SwV3_vNE-bIdmSv6o',
    appId: '1:127475219651:ios:27c45fb976cb5dc836b676',
    messagingSenderId: '127475219651',
    projectId: 'my-netflix-dup',
    storageBucket: 'my-netflix-dup.appspot.com',
    iosBundleId: 'com.example.netflixClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbsgp1NVQLla381SwV3_vNE-bIdmSv6o',
    appId: '1:127475219651:ios:27c45fb976cb5dc836b676',
    messagingSenderId: '127475219651',
    projectId: 'my-netflix-dup',
    storageBucket: 'my-netflix-dup.appspot.com',
    iosBundleId: 'com.example.netflixClone',
  );
}
